development:
  cloud_name: 'dx0uzywra'
  api_key: '934926226299792'
  api_secret: 'qdnnYYQo8qSBefC-lRyrVZnui-w'
  secure: true

production:
  cloud_name: 'dx0uzywra'
  api_key: '934926226299792'
  api_secret: 'qdnnYYQo8qSBefC-lRyrVZnui-w'
  secure: true