development:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_ACCESS_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET_KEY'] %>
  secure: true

production:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_ACCESS_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_SECRET_KEY'] %> 
  secure: true